### ISSUE TITLE
读取wz文件报错

### ISSUE THREAD

**Issue by RongleCat** [stallpool/maplestory#1]
用v182冒险岛的文件读取部分报无法解码文件，部分报数组读取错误，大佬有遇到过嘛，我看项目中用到的wz版本是062
![image](https://user-images.githubusercontent.com/15684751/131328027-b4eacd70-734f-4bc7-b63e-51a8dc8a4ef1.png)

**Comment by dna2github** [comment]
我去试试啊。估计是哪里decode的时候没有处理好。原版c的是都可以的，062 083和18x都测过；js的只测过062和083。

**Comment by dna2github** [comment]
#2 修复了，现在可以读取了。sorry and enjoy。
